const people = [
  {
    name: "praveen",
    age: 36,
    gender: "male",
    city: "hyderabad",
    salary: 10000,
    image: "https://picsum.photos/seed/praveen/200",
  },
  {
    name: "srikanth",
    age: 32,
    gender: "male",
    city: "bangaluru",
    salary: 20000,
    image: "https://picsum.photos/seed/srikanth/200",
  },
  {
    name: "pradeep",
    age: 21,
    gender: "male",
    city: "hyderabad",
    salary: 25000,
    image: "https://picsum.photos/seed/pradeep/200",
  },
  {
    name: "mounika",
    age: 20,
    gender: "female",
    city: "nalgonda",
    salary: 30000,
    image: "https://picsum.photos/seed/mounika/200",
  },
  {
    name: "nikhil",
    age: 22,
    gender: "male",
    city: "guntur",
    salary: 2000,
    image: "https://picsum.photos/seed/nikhil/200",
  },
  {
    name: "riya",
    age: 14,
    gender: "female",
    city: "indore",
    salary: 40000,
    image: "https://picsum.photos/seed/riya/200",
  },

  {
    name: "arjun",
    age: 28,
    gender: "male",
    city: "delhi",
    salary: 35000,
    image: "https://picsum.photos/seed/arjun/200",
  },
  {
    name: "sneha",
    age: 25,
    gender: "female",
    city: "mumbai",
    salary: 28000,
    image: "https://picsum.photos/seed/sneha/200",
  },
  {
    name: "rahul",
    age: 30,
    gender: "male",
    city: "chennai",
    salary: 45000,
    image: "https://picsum.photos/seed/rahul/200",
  },
  {
    name: "meena",
    age: 27,
    gender: "female",
    city: "pune",
    salary: 22000,
    image: "https://picsum.photos/seed/meena/200",
  },
  {
    name: "varun",
    age: 40,
    gender: "male",
    city: "kolkata",
    salary: 50000,
    image: "https://picsum.photos/seed/varun/200",
  },
  {
    name: "aisha",
    age: 19,
    gender: "female",
    city: "lucknow",
    salary: 15000,
    image: "https://picsum.photos/seed/aisha/200",
  },

  {
    name: "vishal",
    age: 35,
    gender: "male",
    city: "kochi",
    salary: 32000,
    image: "https://picsum.photos/seed/vishal/200",
  },
  {
    name: "anita",
    age: 29,
    gender: "female",
    city: "jaipur",
    salary: 27000,
    image: "https://picsum.photos/seed/anita/200",
  },
  {
    name: "deepak",
    age: 24,
    gender: "male",
    city: "bhopal",
    salary: 18000,
    image: "https://picsum.photos/seed/deepak/200",
  },
  {
    name: "pooja",
    age: 33,
    gender: "female",
    city: "nagpur",
    salary: 37000,
    image: "https://picsum.photos/seed/pooja/200",
  },
  {
    name: "manoj",
    age: 26,
    gender: "male",
    city: "patna",
    salary: 21000,
    image: "https://picsum.photos/seed/manoj/200",
  },
  {
    name: "neha",
    age: 31,
    gender: "female",
    city: "surat",
    salary: 39000,
    image: "https://picsum.photos/seed/neha/200",
  },

  {
    name: "sachin",
    age: 38,
    gender: "male",
    city: "kanpur",
    salary: 60000,
    image: "https://picsum.photos/seed/sachin/200",
  },
  {
    name: "anjali",
    age: 23,
    gender: "female",
    city: "bhubaneswar",
    salary: 25000,
    image: "https://picsum.photos/seed/anjali/200",
  },
  {
    name: "rakesh",
    age: 27,
    gender: "male",
    city: "indore",
    salary: 27000,
    image: "https://picsum.photos/seed/rakesh/200",
  },
  {
    name: "sonali",
    age: 22,
    gender: "female",
    city: "amritsar",
    salary: 16000,
    image: "https://picsum.photos/seed/sonali/200",
  },
  {
    name: "karan",
    age: 29,
    gender: "male",
    city: "vadodara",
    salary: 34000,
    image: "https://picsum.photos/seed/karan/200",
  },
  {
    name: "isha",
    age: 18,
    gender: "female",
    city: "meerut",
    salary: 12000,
    image: "https://picsum.photos/seed/isha/200",
  },

  {
    name: "rohit",
    age: 34,
    gender: "male",
    city: "chandigarh",
    salary: 41000,
    image: "https://picsum.photos/seed/rohit/200",
  },
  {
    name: "kavya",
    age: 28,
    gender: "female",
    city: "coimbatore",
    salary: 23000,
    image: "https://picsum.photos/seed/kavya/200",
  },
  {
    name: "ajay",
    age: 45,
    gender: "male",
    city: "madurai",
    salary: 55000,
    image: "https://picsum.photos/seed/ajay/200",
  },
  {
    name: "lavanya",
    age: 21,
    gender: "female",
    city: "warangal",
    salary: 19000,
    image: "https://picsum.photos/seed/lavanya/200",
  },
  {
    name: "gautam",
    age: 37,
    gender: "male",
    city: "ranchi",
    salary: 36000,
    image: "https://picsum.photos/seed/gautam/200",
  },
  {
    name: "tanya",
    age: 24,
    gender: "female",
    city: "vizag",
    salary: 30000,
    image: "https://picsum.photos/seed/tanya/200",
  },
];
